/* SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause) */
/*
 * Copyright (C) 2020, STMicroelectronics - All Rights Reserved
 */

#ifndef __DT_BINDINGS_REGULATOR_ST_STM32MP15_REGULATOR_H
#define __DT_BINDINGS_REGULATOR_ST_STM32MP15_REGULATOR_H

/* SCMI voltage domain identifiers */

#define VOLTD_SCMI0_REG11		0
#define VOLTD_SCMI0_REG18		1
#define VOLTD_SCMI0_USB33		2

#define VOLTD_SCMI2_BUCK1		0
#define VOLTD_SCMI2_BUCK2		1
#define VOLTD_SCMI2_BUCK3		2
#define VOLTD_SCMI2_BUCK4		3
#define VOLTD_SCMI2_LDO1		4
#define VOLTD_SCMI2_LDO2		5
#define VOLTD_SCMI2_LDO3		6
#define VOLTD_SCMI2_LDO4		7
#define VOLTD_SCMI2_LDO5		8
#define VOLTD_SCMI2_LDO6		9
#define VOLTD_SCMI2_VREFDDR		10
#define VOLTD_SCMI2_BOOTST		11
#define VOLTD_SCMI2_PWR_SW1		12
#define VOLTD_SCMI2_PWR_SW2		13

#endif /*__DT_BINDINGS_REGULATOR_ST_STM32MP15_REGULATOR_H */
